# * Copyright (C) 2021 Universitat Politècnica de Catalunya.
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at:
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.

# PATHS
train_dataset: ../data/train
validation_dataset: ../data/validation
predict_dataset: ../data/test
#warm_start_path:
additional_functions_file: ./main.py
output_path: ./

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
  learning_rate: 0.001
metrics: [MeanAbsolutePercentageError]

# TRAINING OPTIONS
batch_size: 1
epochs: 100
epoch_size: 1000
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 5
val_frequency: 1